# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: adapter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'adapter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\radapter.proto\x12\x0e\x61tp.adapter.v1\"L\n\x0f\x45stimateRequest\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x13\n\x0bprompt_json\x18\x03 \x01(\t\"\x91\x02\n\x10\x45stimateResponse\x12\x11\n\tin_tokens\x18\x01 \x01(\x04\x12\x12\n\nout_tokens\x18\x02 \x01(\x04\x12\x12\n\nusd_micros\x18\x03 \x01(\x04\x12\x12\n\np95_tokens\x18\x04 \x01(\x04\x12\x16\n\x0ep95_usd_micros\x18\x05 \x01(\x04\x12\x17\n\x0fvariance_tokens\x18\x06 \x01(\x01\x12\x14\n\x0cvariance_usd\x18\x07 \x01(\x01\x12\x12\n\nconfidence\x18\x08 \x01(\x01\x12 \n\x18tool_cost_breakdown_json\x18\t \x01(\t\x12\x13\n\x0b\x61ssumptions\x18\n \x03(\t\x12\x1c\n\x14token_estimates_json\x18\x0b \x01(\t\"7\n\rStreamRequest\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x13\n\x0bprompt_json\x18\x02 \x01(\t\"\xa6\x01\n\x0bStreamChunk\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_json\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x19\n\x11partial_in_tokens\x18\x04 \x01(\x04\x12\x1a\n\x12partial_out_tokens\x18\x05 \x01(\x04\x12\x1a\n\x12partial_usd_micros\x18\x06 \x01(\x04\x12\x0c\n\x04more\x18\x07 \x01(\x08\"\x0f\n\rHealthRequest\"4\n\x0eHealthResponse\x12\x0e\n\x06p95_ms\x18\x01 \x01(\x01\x12\x12\n\nerror_rate\x18\x02 \x01(\x01\x32\xf0\x01\n\x0e\x41\x64\x61pterService\x12M\n\x08\x45stimate\x12\x1f.atp.adapter.v1.EstimateRequest\x1a .atp.adapter.v1.EstimateResponse\x12\x46\n\x06Stream\x12\x1d.atp.adapter.v1.StreamRequest\x1a\x1b.atp.adapter.v1.StreamChunk0\x01\x12G\n\x06Health\x12\x1d.atp.adapter.v1.HealthRequest\x1a\x1e.atp.adapter.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adapter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ESTIMATEREQUEST']._serialized_start=33
  _globals['_ESTIMATEREQUEST']._serialized_end=109
  _globals['_ESTIMATERESPONSE']._serialized_start=112
  _globals['_ESTIMATERESPONSE']._serialized_end=385
  _globals['_STREAMREQUEST']._serialized_start=387
  _globals['_STREAMREQUEST']._serialized_end=442
  _globals['_STREAMCHUNK']._serialized_start=445
  _globals['_STREAMCHUNK']._serialized_end=611
  _globals['_HEALTHREQUEST']._serialized_start=613
  _globals['_HEALTHREQUEST']._serialized_end=628
  _globals['_HEALTHRESPONSE']._serialized_start=630
  _globals['_HEALTHRESPONSE']._serialized_end=682
  _globals['_ADAPTERSERVICE']._serialized_start=685
  _globals['_ADAPTERSERVICE']._serialized_end=925
# @@protoc_insertion_point(module_scope)
