"""gRPC client for communicating with ATP adapters.

This module provides asynchronous gRPC client infrastructure for making
requests to external LLM adapters. Adapters implement the AdapterService
protocol defined in adapter.proto.

Example:
    >>> client = AdapterClient("localhost:7073")
    >>> async for chunk in client.stream("Hello, world!"):
    ...     print(chunk["content_json"])
"""

import logging

# Import protobuf definitions from tools directory
import sys
from collections.abc import AsyncIterator
from pathlib import Path
from typing import Any

import grpc

tools_path = Path(__file__).parent.parent.parent / "tools"
sys.path.insert(0, str(tools_path))

try:
    import adapter_pb2
    import adapter_pb2_grpc
finally:
    sys.path.pop(0)

logger = logging.getLogger(__name__)


class AdapterClient:
    """Asynchronous gRPC client for adapter communication.

    This client manages connections to adapter services and provides
    methods for estimation, streaming inference, and health checks.

    Attributes:
        endpoint: gRPC endpoint address (e.g., "localhost:7073")
        timeout: Default request timeout in seconds
    """

    def __init__(self, adapter_endpoint: str, timeout: float = 30.0):
        """Initialize adapter client.

        Args:
            adapter_endpoint: gRPC endpoint (e.g., "localhost:7073")
            timeout: Request timeout in seconds (default: 30.0)
        """
        self.endpoint = adapter_endpoint
        self.timeout = timeout
        self._channel: grpc.aio.Channel | None = None
        self._stub: adapter_pb2_grpc.AdapterServiceStub | None = None

    async def connect(self) -> None:
        """Establish gRPC connection to adapter.

        This method is idempotent - calling it multiple times will not
        create duplicate connections.
        """
        if self._channel is None:
            self._channel = grpc.aio.insecure_channel(self.endpoint)
            self._stub = adapter_pb2_grpc.AdapterServiceStub(self._channel)
            logger.info(f"Connected to adapter at {self.endpoint}")

    async def close(self) -> None:
        """Close gRPC connection and cleanup resources."""
        if self._channel:
            await self._channel.close()
            self._channel = None
            self._stub = None
            logger.info(f"Closed connection to adapter at {self.endpoint}")

    async def estimate(
        self, prompt: str, task_type: str = "completion", stream_id: str | None = None
    ) -> dict[str, Any]:
        """Get cost and token estimate for a prompt.

        Args:
            prompt: User prompt text
            task_type: Type of task (completion, chat, etc.)
            stream_id: Optional stream identifier

        Returns:
            Dictionary containing:
                - in_tokens: Estimated input tokens
                - out_tokens: Estimated output tokens
                - usd_micros: Estimated cost in USD micros (1 USD = 1,000,000 micros)
                - p95_tokens: 95th percentile token estimate
                - p95_usd_micros: 95th percentile cost estimate
                - confidence: Confidence score (0.0-1.0)

        Raises:
            grpc.RpcError: If the RPC call fails
        """
        await self.connect()

        request = adapter_pb2.EstimateRequest(stream_id=stream_id or "", task_type=task_type, prompt_json=prompt)

        try:
            response = await self._stub.Estimate(request, timeout=self.timeout)
            return {
                "in_tokens": response.in_tokens,
                "out_tokens": response.out_tokens,
                "usd_micros": response.usd_micros,
                "p95_tokens": response.p95_tokens,
                "p95_usd_micros": response.p95_usd_micros,
                "confidence": response.confidence,
            }
        except grpc.RpcError as e:
            logger.error(f"Estimate RPC failed for {self.endpoint}: {e.code()} - {e.details()}")
            raise

    async def stream(self, prompt: str, stream_id: str | None = None) -> AsyncIterator[dict[str, Any]]:
        """Stream inference results from adapter.

        This method yields chunks as they are generated by the adapter.
        Each chunk contains partial results and metadata.

        Args:
            prompt: User prompt (can be JSON for complex requests)
            stream_id: Optional stream identifier

        Yields:
            Dictionary chunks containing:
                - type: Chunk type ("text", "tool_call", "done")
                - content_json: JSON-encoded content
                - confidence: Confidence score
                - partial_in_tokens: Cumulative input tokens
                - partial_out_tokens: Cumulative output tokens
                - partial_usd_micros: Cumulative cost in USD micros
                - more: True if more chunks are coming

        Raises:
            grpc.RpcError: If the RPC call fails

        Example:
            >>> client = AdapterClient("localhost:7073")
            >>> async for chunk in client.stream("Hello!"):
            ...     if chunk["type"] == "text":
            ...         print(chunk["content_json"])
        """
        await self.connect()

        request = adapter_pb2.StreamRequest(stream_id=stream_id or "", prompt_json=prompt)

        try:
            async for chunk in self._stub.Stream(request, timeout=self.timeout):
                yield {
                    "type": chunk.type,
                    "content_json": chunk.content_json,
                    "confidence": chunk.confidence,
                    "partial_in_tokens": chunk.partial_in_tokens,
                    "partial_out_tokens": chunk.partial_out_tokens,
                    "partial_usd_micros": chunk.partial_usd_micros,
                    "more": chunk.more,
                }
        except grpc.RpcError as e:
            logger.error(f"Stream RPC failed for {self.endpoint}: {e.code()} - {e.details()}")
            raise

    async def health(self) -> dict[str, Any]:
        """Check adapter health and get performance metrics.

        Returns:
            Dictionary containing:
                - p95_ms: 95th percentile latency in milliseconds
                - error_rate: Error rate (0.0-1.0)

        Raises:
            grpc.RpcError: If the RPC call fails
        """
        await self.connect()

        request = adapter_pb2.HealthRequest()

        try:
            response = await self._stub.Health(request, timeout=5.0)
            return {
                "p95_ms": response.p95_ms,
                "error_rate": response.error_rate,
            }
        except grpc.RpcError as e:
            logger.error(f"Health RPC failed for {self.endpoint}: {e.code()} - {e.details()}")
            raise


class AdapterClientPool:
    """Connection pool for managing multiple adapter clients.

    This pool maintains a cache of AdapterClient instances, reusing
    connections to the same endpoints to reduce overhead.

    Example:
        >>> pool = AdapterClientPool()
        >>> client = pool.get_client("localhost:7073")
        >>> async for chunk in client.stream("Hello!"):
        ...     print(chunk)
        >>> await pool.close_all()  # Cleanup on shutdown
    """

    def __init__(self):
        """Initialize empty client pool."""
        self._clients: dict[str, AdapterClient] = {}

    def get_client(self, adapter_endpoint: str, timeout: float = 30.0) -> AdapterClient:
        """Get or create client for the specified endpoint.

        This method returns a cached client if one exists for the endpoint,
        or creates a new one otherwise.

        Args:
            adapter_endpoint: gRPC endpoint address
            timeout: Request timeout in seconds

        Returns:
            AdapterClient instance for the endpoint
        """
        if adapter_endpoint not in self._clients:
            self._clients[adapter_endpoint] = AdapterClient(adapter_endpoint, timeout)
            logger.info(f"Created new adapter client for {adapter_endpoint}")
        return self._clients[adapter_endpoint]

    async def close_all(self) -> None:
        """Close all client connections and clear the pool.

        This method should be called during application shutdown to
        ensure all gRPC connections are properly closed.
        """
        for endpoint, client in self._clients.items():
            await client.close()
            logger.info(f"Closed client for {endpoint}")
        self._clients.clear()
        logger.info("Adapter client pool cleared")

    def get_active_clients(self) -> list[str]:
        """Get list of endpoints with active clients.

        Returns:
            List of endpoint addresses
        """
        return list(self._clients.keys())
