"""Metrics package exposing REGISTRY and metric classes."""

from .registry import (
    # GAP-328: Access review attestation workflow metrics
    ACCESS_REVIEWS_COMPLETED_TOTAL,
    # GAP-329: Config drift & security baseline detector metrics
    CONFIG_DRIFT_ALERTS_TOTAL,
    # GAP-271: DP telemetry exporter metrics
    DP_EVENTS_EXPORTED_TOTAL,
    # GAP-371: Federated reward signal schema metrics
    FEDERATED_REWARD_BATCHES_TOTAL,
    # GAP-220: Federated routing prior aggregator metrics
    FEDERATED_ROUNDS_COMPLETED,
    # GAP-310: Cross-namespace access audit & anomaly detection metrics
    MEMORY_ACCESS_ANOMALIES_TOTAL,
    MERKLE_ROOT_PUBLISH_LATENCY,
    # GAP-329C: Audit Merkle root anchoring strategy metrics
    MERKLE_ROOT_PUBLISH_TOTAL,
    MERKLE_ROOT_VERIFICATION_FAILED_TOTAL,
    MERKLE_ROOT_VERIFICATION_TOTAL,
    POLICY_APPROVAL_LATENCY,
    POLICY_CHANGE_REQUESTS_APPROVED_TOTAL,
    POLICY_CHANGE_REQUESTS_EXPIRED_TOTAL,
    POLICY_CHANGE_REQUESTS_PENDING,
    POLICY_CHANGE_REQUESTS_REJECTED_TOTAL,
    # GAP-162: Policy change approval workflow metrics
    POLICY_CHANGE_REQUESTS_TOTAL,
    REEMBED_BATCHES_PROCESSED_TOTAL,
    REEMBED_ITEMS_REEMBEDDED_TOTAL,
    REEMBED_JOBS_ACTIVE,
    # GAP-309: Vector backfill & re-embedding pipeline metrics
    REEMBED_JOBS_COMPLETED_TOTAL,
    REEMBED_JOBS_FAILED_TOTAL,
    REEMBED_JOBS_QUEUED,
    REGISTRY,
    # GAP-372: Secure aggregation protocol metrics
    SECURE_AGG_FAILURES_TOTAL,
    # GAP-329D: SLA tier specification & SLO targets metrics
    SLO_BREACH_EVENTS_TOTAL,
    # GAP-329B: Vector DB certification matrix metrics
    VECTOR_BACKEND_RECALL_AT_K_IN_MEMORY,
    VECTOR_BACKEND_RECALL_AT_K_PGVECTOR,
    VECTOR_BACKEND_RECALL_AT_K_PINECONE,
    VECTOR_BACKEND_RECALL_AT_K_WEAVIATE,
    Counter,
    Gauge,
    Histogram,
    MetricsRegistry,
)  # noqa: F401

__all__ = [
    "REGISTRY",
    "Counter",
    "Gauge",
    "Histogram",
    "MetricsRegistry",
    "REEMBED_JOBS_COMPLETED_TOTAL",
    "REEMBED_JOBS_FAILED_TOTAL",
    "REEMBED_JOBS_ACTIVE",
    "REEMBED_JOBS_QUEUED",
    "REEMBED_BATCHES_PROCESSED_TOTAL",
    "REEMBED_ITEMS_REEMBEDDED_TOTAL",
    "MEMORY_ACCESS_ANOMALIES_TOTAL",
    "DP_EVENTS_EXPORTED_TOTAL",
    "FEDERATED_ROUNDS_COMPLETED",
    "FEDERATED_REWARD_BATCHES_TOTAL",
    "SECURE_AGG_FAILURES_TOTAL",
    "POLICY_CHANGE_REQUESTS_TOTAL",
    "POLICY_CHANGE_REQUESTS_APPROVED_TOTAL",
    "POLICY_CHANGE_REQUESTS_REJECTED_TOTAL",
    "POLICY_CHANGE_REQUESTS_EXPIRED_TOTAL",
    "POLICY_CHANGE_REQUESTS_PENDING",
    "POLICY_APPROVAL_LATENCY",
    "ACCESS_REVIEWS_COMPLETED_TOTAL",
    "CONFIG_DRIFT_ALERTS_TOTAL",
    "VECTOR_BACKEND_RECALL_AT_K_IN_MEMORY",
    "VECTOR_BACKEND_RECALL_AT_K_WEAVIATE",
    "VECTOR_BACKEND_RECALL_AT_K_PINECONE",
    "VECTOR_BACKEND_RECALL_AT_K_PGVECTOR",
    "MERKLE_ROOT_PUBLISH_TOTAL",
    "MERKLE_ROOT_VERIFICATION_TOTAL",
    "MERKLE_ROOT_VERIFICATION_FAILED_TOTAL",
    "MERKLE_ROOT_PUBLISH_LATENCY",
    "SLO_BREACH_EVENTS_TOTAL",
]
